spring:
  profiles:
    active:
      - dev

logging:
  path: logs
server:
  port: 8081


---
spring:
  profiles: dev
  redis:
    host: 192.168.120.3
    port: 6379
    database: 0
    pool:
      min-idle: 2

dber:
  service:
    name: plat
    database:
      host: 192.168.120.3
      port: 3306
      database: dber_plat
      username: root
      password: 123456
      parameters: characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true
      initialSize: 1
      maxActive: 2
      minIdle: 1
  web:
    baseUrl: http://127.0.0.1:8081/
      
      
